"""Tests for lib/sops.py - YAML schema v2 (nested profiles map).

The SOPS secrets file format changed in the multi-identity refactor:

v1 (legacy, still readable):
    certificate: ...
    private_key: ...
    trust_anchor_arn: ...
    profile_arn: ...         # single
    role_arn: ...            # single
    region: ...

v2 (current, written by iam-ra host onboard):
    schema_version: v2
    certificate: ...
    private_key: ...
    trust_anchor_arn: ...
    account_id: ...
    region: ...
    profiles:                # map keyed by role name
      admin:
        profile_arn: ...
        role_arn: ...
      readonly:
        profile_arn: ...
        role_arn: ...

parse_secrets_yaml() accepts both shapes; writes always emit v2.
"""

import pytest
import yaml

from iam_ra_cli.lib.sops import (
    SOPS_SCHEMA_VERSION,
    SopsProfile,
    SopsSecrets,
    create_secrets_yaml,
    parse_secrets_yaml,
)

# =============================================================================
# Fixtures: minimal realistic v1 / v2 content as raw YAML (strings)
# =============================================================================


V1_YAML = """\
# IAM Roles Anywhere secrets for myhost
# Generated by iam-ra-cli v2.x
certificate: |
  -----BEGIN CERTIFICATE-----
  v1cert
  -----END CERTIFICATE-----
private_key: |
  -----BEGIN EC PRIVATE KEY-----
  v1key
  -----END EC PRIVATE KEY-----
trust_anchor_arn: arn:aws:rolesanywhere:ap-southeast-2:111122223333:trust-anchor/v1-ta
profile_arn: arn:aws:rolesanywhere:ap-southeast-2:111122223333:profile/admin-p
role_arn: arn:aws:iam::111122223333:role/admin
region: ap-southeast-2
"""


V2_YAML = """\
schema_version: v2
certificate: |
  -----BEGIN CERTIFICATE-----
  v2cert
  -----END CERTIFICATE-----
private_key: |
  -----BEGIN EC PRIVATE KEY-----
  v2key
  -----END EC PRIVATE KEY-----
trust_anchor_arn: arn:aws:rolesanywhere:ap-southeast-2:444455556666:trust-anchor/v2-ta
account_id: "444455556666"
region: ap-southeast-2
profiles:
  admin:
    profile_arn: arn:aws:rolesanywhere:ap-southeast-2:444455556666:profile/admin-p
    role_arn: arn:aws:iam::444455556666:role/admin
  readonly:
    profile_arn: arn:aws:rolesanywhere:ap-southeast-2:444455556666:profile/readonly-p
    role_arn: arn:aws:iam::444455556666:role/readonly
"""


# =============================================================================
# Schema constant
# =============================================================================


class TestSchemaConstant:
    def test_schema_version_is_v2(self) -> None:
        """Lock the constant: v2 is the current SOPS schema."""
        assert SOPS_SCHEMA_VERSION == "v2"


# =============================================================================
# create_secrets_yaml (writes v2)
# =============================================================================


class TestCreateSecretsYamlV2:
    """create_secrets_yaml must emit the v2 schema."""

    def _make_secrets(
        self,
        profiles: tuple[SopsProfile, ...] = (
            SopsProfile(
                role_name="admin",
                profile_arn="arn:aws:rolesanywhere:ap-southeast-2:123:profile/admin-p",
                role_arn="arn:aws:iam::123:role/admin",
            ),
        ),
    ) -> SopsSecrets:
        return SopsSecrets(
            certificate="CERT-PEM",
            private_key="KEY-PEM",
            trust_anchor_arn=(
                "arn:aws:rolesanywhere:ap-southeast-2:123:trust-anchor/ta"
            ),
            account_id="123456789012",
            region="ap-southeast-2",
            profiles=profiles,
        )

    def test_includes_schema_version(self) -> None:
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=self._make_secrets())
        data = yaml.safe_load(yaml_text)
        assert data["schema_version"] == "v2"

    def test_top_level_fields(self) -> None:
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=self._make_secrets())
        data = yaml.safe_load(yaml_text)
        assert data["certificate"] == "CERT-PEM"
        assert data["private_key"] == "KEY-PEM"
        assert "trust-anchor" in data["trust_anchor_arn"]
        assert data["account_id"] == "123456789012"
        assert data["region"] == "ap-southeast-2"

    def test_profiles_is_nested_map(self) -> None:
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=self._make_secrets())
        data = yaml.safe_load(yaml_text)
        assert "profiles" in data
        assert isinstance(data["profiles"], dict)
        assert "admin" in data["profiles"]
        assert "profile_arn" in data["profiles"]["admin"]
        assert "role_arn" in data["profiles"]["admin"]

    def test_multi_profile_output(self) -> None:
        secrets = self._make_secrets(
            profiles=(
                SopsProfile(
                    role_name="admin",
                    profile_arn="arn:aws:rolesanywhere:ap-southeast-2:123:profile/admin-p",
                    role_arn="arn:aws:iam::123:role/admin",
                ),
                SopsProfile(
                    role_name="readonly",
                    profile_arn="arn:aws:rolesanywhere:ap-southeast-2:123:profile/readonly-p",
                    role_arn="arn:aws:iam::123:role/readonly",
                ),
            ),
        )
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=secrets)
        data = yaml.safe_load(yaml_text)
        assert set(data["profiles"].keys()) == {"admin", "readonly"}
        assert (
            data["profiles"]["admin"]["role_arn"] == "arn:aws:iam::123:role/admin"
        )
        assert (
            data["profiles"]["readonly"]["role_arn"]
            == "arn:aws:iam::123:role/readonly"
        )

    def test_header_comment_references_hostname(self) -> None:
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=self._make_secrets())
        assert "myhost" in yaml_text
        assert yaml_text.startswith("#")  # has a header

    def test_no_scalar_profile_arn_or_role_arn_at_top_level(self) -> None:
        """v2 must not emit the v1 singular fields - they'd be ambiguous."""
        yaml_text = create_secrets_yaml(hostname="myhost", secrets=self._make_secrets())
        data = yaml.safe_load(yaml_text)
        assert "profile_arn" not in data
        assert "role_arn" not in data


# =============================================================================
# parse_secrets_yaml (reads v1 and v2)
# =============================================================================


class TestParseSecretsYamlV2:
    """Reading a v2 YAML returns a matching SopsSecrets record."""

    def test_parses_all_fields(self) -> None:
        secrets = parse_secrets_yaml(V2_YAML)

        assert secrets.certificate.startswith("-----BEGIN CERTIFICATE-----")
        assert "v2cert" in secrets.certificate
        assert secrets.private_key.startswith("-----BEGIN EC PRIVATE KEY-----")
        assert (
            secrets.trust_anchor_arn
            == "arn:aws:rolesanywhere:ap-southeast-2:444455556666:trust-anchor/v2-ta"
        )
        assert secrets.account_id == "444455556666"
        assert secrets.region == "ap-southeast-2"

    def test_parses_profiles_as_tuple(self) -> None:
        secrets = parse_secrets_yaml(V2_YAML)

        assert len(secrets.profiles) == 2
        by_name = {p.role_name: p for p in secrets.profiles}
        assert set(by_name.keys()) == {"admin", "readonly"}
        assert by_name["admin"].role_arn == "arn:aws:iam::444455556666:role/admin"
        assert (
            by_name["readonly"].profile_arn
            == "arn:aws:rolesanywhere:ap-southeast-2:444455556666:profile/readonly-p"
        )

    def test_roundtrip_write_read(self) -> None:
        """Writing then reading v2 must preserve all fields exactly."""
        original = SopsSecrets(
            certificate="CERT",
            private_key="KEY",
            trust_anchor_arn="arn:aws:rolesanywhere:ap-southeast-2:123:trust-anchor/ta",
            account_id="123456789012",
            region="us-east-1",
            profiles=(
                SopsProfile(
                    role_name="admin",
                    profile_arn="arn:aws:rolesanywhere:us-east-1:123:profile/admin-p",
                    role_arn="arn:aws:iam::123:role/admin",
                ),
                SopsProfile(
                    role_name="readonly",
                    profile_arn="arn:aws:rolesanywhere:us-east-1:123:profile/readonly-p",
                    role_arn="arn:aws:iam::123:role/readonly",
                ),
            ),
        )
        yaml_text = create_secrets_yaml(hostname="roundtrip-host", secrets=original)
        restored = parse_secrets_yaml(yaml_text)

        assert restored.certificate == original.certificate
        assert restored.private_key == original.private_key
        assert restored.trust_anchor_arn == original.trust_anchor_arn
        assert restored.account_id == original.account_id
        assert restored.region == original.region
        # Order-insensitive compare (dict iteration may differ)
        assert set(restored.profiles) == set(original.profiles)


class TestParseSecretsYamlV1Fallback:
    """v1 YAML (flat single profile_arn/role_arn) auto-converts to v2 shape."""

    def test_parses_v1_fields(self) -> None:
        secrets = parse_secrets_yaml(V1_YAML)

        assert "v1cert" in secrets.certificate
        assert "v1key" in secrets.private_key
        assert secrets.region == "ap-southeast-2"
        assert (
            secrets.trust_anchor_arn
            == "arn:aws:rolesanywhere:ap-southeast-2:111122223333:trust-anchor/v1-ta"
        )

    def test_v1_account_id_derived_from_trust_anchor(self) -> None:
        """v1 had no account_id field - parser derives from trust_anchor_arn."""
        secrets = parse_secrets_yaml(V1_YAML)
        assert secrets.account_id == "111122223333"

    def test_v1_single_profile_lifted_into_profiles_map(self) -> None:
        """v1's scalar profile_arn+role_arn become a single entry in profiles."""
        secrets = parse_secrets_yaml(V1_YAML)
        assert len(secrets.profiles) == 1
        p = secrets.profiles[0]
        # v1 has no role name anywhere - derive from role ARN resource name
        # (the part after role/) so add-role has a stable map key to index on.
        assert p.role_name == "admin"
        assert p.role_arn == "arn:aws:iam::111122223333:role/admin"
        assert (
            p.profile_arn
            == "arn:aws:rolesanywhere:ap-southeast-2:111122223333:profile/admin-p"
        )


class TestParseSecretsYamlErrors:
    """Invalid / unsupported schema versions should fail loud."""

    def test_missing_required_v2_field_raises(self) -> None:
        broken = """\
schema_version: v2
certificate: CERT
private_key: KEY
# trust_anchor_arn missing
account_id: "123456789012"
region: us-east-1
profiles: {}
"""
        with pytest.raises(ValueError, match="trust_anchor_arn"):
            parse_secrets_yaml(broken)

    def test_unknown_schema_version_raises(self) -> None:
        future = """\
schema_version: v99
certificate: CERT
private_key: KEY
"""
        with pytest.raises(ValueError, match="schema_version"):
            parse_secrets_yaml(future)

    def test_empty_yaml_raises(self) -> None:
        with pytest.raises(ValueError):
            parse_secrets_yaml("")


# =============================================================================
# Path resolution (namespace-aware, legacy fallback)
# =============================================================================


class TestGetSecretsPath:
    """get_secrets_path is the canonical write path.

    Always returns the namespace-suffixed form. Callers that need to
    handle pre-multi-identity files use resolve_existing_secrets_path.
    """

    def test_default_namespace_suffix(self, tmp_path) -> None:
        from iam_ra_cli.lib.sops import get_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        path = get_secrets_path("myhost", namespace="default", repo_root=tmp_path)

        assert path == tmp_path / "secrets" / "hosts" / "myhost" / "iam-ra-default.yaml"

    def test_non_default_namespace_suffix(self, tmp_path) -> None:
        from iam_ra_cli.lib.sops import get_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        path = get_secrets_path("myhost", namespace="work", repo_root=tmp_path)

        assert path == tmp_path / "secrets" / "hosts" / "myhost" / "iam-ra-work.yaml"

    def test_namespace_defaults_to_default(self, tmp_path) -> None:
        """Omitting namespace must resolve as namespace='default' for
        backward-compat with existing callers."""
        from iam_ra_cli.lib.sops import get_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        path = get_secrets_path("myhost", repo_root=tmp_path)

        assert path.name == "iam-ra-default.yaml"


class TestResolveExistingSecretsPath:
    """resolve_existing_secrets_path handles the legacy `iam-ra.yaml`
    (pre-multi-identity) for the default namespace, warning the user to
    run the explicit migrate command.

    Contract:
      - Canonical path exists -> return (canonical, is_legacy=False).
      - Canonical missing, legacy exists, namespace=default ->
        return (legacy, is_legacy=True).
      - Canonical missing, legacy missing or non-default namespace ->
        return (canonical, is_legacy=False). Caller gets a path to a
        non-existent file to react on (FileNotFoundError on read).
    """

    def test_canonical_wins_when_both_exist(self, tmp_path) -> None:
        from iam_ra_cli.lib.sops import resolve_existing_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        host_dir = tmp_path / "secrets" / "hosts" / "myhost"
        host_dir.mkdir(parents=True)
        canonical = host_dir / "iam-ra-default.yaml"
        legacy = host_dir / "iam-ra.yaml"
        canonical.write_text("canonical")
        legacy.write_text("legacy")

        path, is_legacy = resolve_existing_secrets_path(
            "myhost", namespace="default", repo_root=tmp_path
        )

        assert path == canonical
        assert is_legacy is False

    def test_falls_back_to_legacy_for_default_namespace(self, tmp_path) -> None:
        from iam_ra_cli.lib.sops import resolve_existing_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        host_dir = tmp_path / "secrets" / "hosts" / "myhost"
        host_dir.mkdir(parents=True)
        legacy = host_dir / "iam-ra.yaml"
        legacy.write_text("legacy-only")

        path, is_legacy = resolve_existing_secrets_path(
            "myhost", namespace="default", repo_root=tmp_path
        )

        assert path == legacy
        assert is_legacy is True

    def test_no_legacy_fallback_for_non_default_namespace(self, tmp_path) -> None:
        """Legacy file (iam-ra.yaml) is only ambiguous in the default-namespace
        case. For other namespaces, a legacy file near a non-default
        canonical path doesn't mean anything and shouldn't be silently
        consumed."""
        from iam_ra_cli.lib.sops import resolve_existing_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        host_dir = tmp_path / "secrets" / "hosts" / "myhost"
        host_dir.mkdir(parents=True)
        legacy = host_dir / "iam-ra.yaml"
        legacy.write_text("legacy")  # for the default namespace conceptually

        path, is_legacy = resolve_existing_secrets_path(
            "myhost", namespace="work", repo_root=tmp_path
        )

        # Doesn't find anything - returns canonical (which doesn't exist)
        assert path == host_dir / "iam-ra-work.yaml"
        assert is_legacy is False

    def test_nothing_exists_returns_canonical(self, tmp_path) -> None:
        from iam_ra_cli.lib.sops import resolve_existing_secrets_path

        (tmp_path / "flake.nix").write_text("{}")
        path, is_legacy = resolve_existing_secrets_path(
            "myhost", namespace="default", repo_root=tmp_path
        )

        assert path.name == "iam-ra-default.yaml"
        assert is_legacy is False
