"""SOPS integration for IAM Roles Anywhere CLI."""

import subprocess
from pathlib import Path

import yaml


def create_secrets_yaml(
    hostname: str,
    certificate: str,
    private_key: str,
    trust_anchor_arn: str,
    profile_arn: str,
    role_arn: str,
    region: str,
) -> str:
    """
    Create YAML content for IAM Roles Anywhere secrets.

    Args:
        hostname: Host identifier
        certificate: X.509 certificate PEM
        private_key: Private key PEM
        trust_anchor_arn: Trust Anchor ARN
        profile_arn: IAM Roles Anywhere Profile ARN
        role_arn: IAM Role ARN
        region: AWS region

    Returns:
        YAML string (unencrypted)
    """
    data = {
        "certificate": certificate,
        "private_key": private_key,
        "trust_anchor_arn": trust_anchor_arn,
        "profile_arn": profile_arn,
        "role_arn": role_arn,
        "region": region,
    }

    # Add header comment
    header = f"""# IAM Roles Anywhere secrets for {hostname}
# Generated by iam-ra-cli
# Encrypted with SOPS before commit

"""
    return header + yaml.dump(data, default_flow_style=False, allow_unicode=True)


def write_and_encrypt(
    content: str,
    output_path: Path,
    sops_config_path: Path | None = None,
) -> None:
    """
    Write YAML content to a file and encrypt it with SOPS.

    Args:
        content: YAML content to write
        output_path: Path to write the encrypted file
        sops_config_path: Optional path to .sops.yaml config

    Raises:
        subprocess.CalledProcessError: If SOPS encryption fails
    """
    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write unencrypted content first
    output_path.write_text(content)

    # Build sops command
    cmd = ["sops", "-e", "-i"]

    if sops_config_path:
        cmd.extend(["--config", str(sops_config_path)])

    cmd.append(str(output_path))

    # Run sops encryption
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        # If encryption fails, remove the unencrypted file
        output_path.unlink(missing_ok=True)
        raise RuntimeError(f"SOPS encryption failed: {e.stderr}") from e


def decrypt_file(
    file_path: Path,
    sops_config_path: Path | None = None,
) -> str:
    """
    Decrypt a SOPS-encrypted file and return its contents.

    Args:
        file_path: Path to the encrypted file
        sops_config_path: Optional path to .sops.yaml config

    Returns:
        Decrypted file contents

    Raises:
        subprocess.CalledProcessError: If SOPS decryption fails
    """
    cmd = ["sops", "-d"]

    if sops_config_path:
        cmd.extend(["--config", str(sops_config_path)])

    cmd.append(str(file_path))

    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return result.stdout


def get_nix_repo_root() -> Path | None:
    """
    Find the root of the Nix repository by looking for flake.nix.

    Returns:
        Path to repository root, or None if not found
    """
    current = Path.cwd()

    while current != current.parent:
        if (current / "flake.nix").exists():
            return current
        current = current.parent

    return None


def get_secrets_path(hostname: str, repo_root: Path | None = None) -> Path:
    """
    Get the path where host secrets should be stored.

    Args:
        hostname: Host identifier
        repo_root: Optional repository root path

    Returns:
        Path to the secrets file
    """
    if repo_root is None:
        repo_root = get_nix_repo_root()

    if repo_root is None:
        raise RuntimeError("Could not find Nix repository root (flake.nix)")

    return repo_root / "secrets" / "hosts" / hostname / "iam-ra.yaml"
