"""SOPS integration for IAM Roles Anywhere CLI.

The secrets file format is versioned:

- **v1** (legacy, read-only): a flat YAML with scalar ``profile_arn`` /
  ``role_arn``. Written by iam-ra <= 2.4; still readable via the v1-fallback
  in :func:`parse_secrets_yaml`.
- **v2** (current): ``schema_version: v2`` marker, explicit
  ``account_id`` field, and a nested ``profiles`` map keyed by role name.
  Always written by :func:`create_secrets_yaml`. Supports multi-role hosts
  (scenario 2 of the multi-identity plan).
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

import yaml

SOPS_SCHEMA_VERSION = "v2"


@dataclass(frozen=True)
class SopsProfile:
    """One entry inside a v2 SOPS file's ``profiles`` map.

    ``role_name`` is the human-readable role identifier (also the map key
    in the YAML). For v1 files that have no role_name metadata, the parser
    derives it from the role ARN's resource name (e.g. the suffix after
    ``role/`` in an IAM role ARN).
    """

    role_name: str
    profile_arn: str
    role_arn: str


@dataclass(frozen=True)
class SopsSecrets:
    """Structured contents of a SOPS secrets file (post-parse).

    Always in v2 shape regardless of the source file version - parsing a
    v1 file promotes its scalar profile/role into a single-entry
    ``profiles`` tuple so callers don't need to branch.
    """

    certificate: str
    private_key: str
    trust_anchor_arn: str
    account_id: str
    region: str
    profiles: tuple[SopsProfile, ...]


def create_secrets_yaml(hostname: str, secrets: SopsSecrets) -> str:
    """Render a ``SopsSecrets`` into v2 YAML.

    Writes the ``schema_version: v2`` marker, top-level cert/key/ARNs, and
    a nested ``profiles`` map. The YAML is unencrypted; callers hand it to
    :func:`write_and_encrypt` for SOPS encryption at rest.

    Args:
        hostname: Host identifier, used in the header comment only.
        secrets: Structured secrets to serialise.

    Returns:
        YAML string (unencrypted).
    """
    data = {
        "schema_version": SOPS_SCHEMA_VERSION,
        "certificate": secrets.certificate,
        "private_key": secrets.private_key,
        "trust_anchor_arn": secrets.trust_anchor_arn,
        "account_id": secrets.account_id,
        "region": secrets.region,
        "profiles": {
            p.role_name: {
                "profile_arn": p.profile_arn,
                "role_arn": p.role_arn,
            }
            for p in secrets.profiles
        },
    }

    header = (
        f"# IAM Roles Anywhere secrets for {hostname}\n"
        f"# Generated by iam-ra-cli\n"
        f"# Encrypted with SOPS before commit\n"
        f"# Schema: {SOPS_SCHEMA_VERSION}\n"
        f"\n"
    )
    return header + yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)


def parse_secrets_yaml(yaml_text: str) -> SopsSecrets:
    """Parse a SOPS YAML (v1 or v2) into a ``SopsSecrets``.

    v1 files are auto-upgraded into the v2 shape in memory:
        - ``account_id`` derived from ``trust_anchor_arn``
        - ``profile_arn`` + ``role_arn`` lifted into a single-entry
          ``profiles`` tuple, keyed by the IAM role's resource name
          (e.g. ``admin`` from ``arn:aws:iam::...:role/admin``).

    Args:
        yaml_text: Decrypted YAML content.

    Returns:
        A ``SopsSecrets`` with fields filled in regardless of source version.

    Raises:
        ValueError: if the YAML is empty, malformed, missing required
            fields, or declares an unsupported ``schema_version``.
    """
    if not yaml_text or not yaml_text.strip():
        raise ValueError("Empty SOPS YAML content")

    data = yaml.safe_load(yaml_text)
    if not isinstance(data, dict):
        raise ValueError("SOPS YAML must parse to a mapping")

    schema_version = data.get("schema_version")

    if schema_version == SOPS_SCHEMA_VERSION:
        return _parse_v2(data)
    elif schema_version is None:
        # No version marker = v1 (legacy). Auto-upgrade in memory.
        return _parse_v1(data)
    else:
        raise ValueError(
            f"Unsupported SOPS schema_version {schema_version!r}; "
            f"this iam-ra understands {SOPS_SCHEMA_VERSION!r} or the pre-v2 "
            f"legacy format (no schema_version key)."
        )


def _parse_v2(data: dict) -> SopsSecrets:
    """v2: requires nested profiles map + account_id."""
    required = (
        "certificate",
        "private_key",
        "trust_anchor_arn",
        "account_id",
        "region",
        "profiles",
    )
    for field in required:
        if field not in data:
            raise ValueError(f"v2 SOPS YAML missing required field: {field}")

    profiles_raw = data["profiles"]
    if not isinstance(profiles_raw, dict):
        raise ValueError("v2 SOPS 'profiles' must be a mapping keyed by role name")

    profiles = tuple(
        SopsProfile(
            role_name=name,
            profile_arn=body["profile_arn"],
            role_arn=body["role_arn"],
        )
        for name, body in profiles_raw.items()
    )

    return SopsSecrets(
        certificate=data["certificate"],
        private_key=data["private_key"],
        trust_anchor_arn=data["trust_anchor_arn"],
        account_id=str(data["account_id"]),
        region=data["region"],
        profiles=profiles,
    )


def _parse_v1(data: dict) -> SopsSecrets:
    """Legacy v1: flat scalar profile_arn/role_arn + no schema_version.

    Upgrade path:
    - account_id derived from trust_anchor_arn's account component
    - single profile lifted into a one-entry profiles tuple, keyed by the
      IAM role's resource name (the part after `role/`)
    """
    required = ("certificate", "private_key", "trust_anchor_arn", "profile_arn", "role_arn", "region")
    for field in required:
        if field not in data:
            raise ValueError(f"v1 SOPS YAML missing required field: {field}")

    trust_anchor_arn = data["trust_anchor_arn"]
    try:
        # ARN format: arn:aws:service:region:account:resource
        account_id = trust_anchor_arn.split(":")[4]
    except (AttributeError, IndexError):
        account_id = ""

    role_arn = data["role_arn"]
    # IAM role ARN: arn:aws:iam::ACCT:role/NAME
    # Extract NAME as the derived role_name; fall back to 'default' for
    # unparseable ARNs so callers always see *some* key.
    try:
        role_name = role_arn.split("/", 1)[1]
    except (AttributeError, IndexError):
        role_name = "default"

    return SopsSecrets(
        certificate=data["certificate"],
        private_key=data["private_key"],
        trust_anchor_arn=trust_anchor_arn,
        account_id=account_id,
        region=data["region"],
        profiles=(
            SopsProfile(
                role_name=role_name,
                profile_arn=data["profile_arn"],
                role_arn=role_arn,
            ),
        ),
    )


def write_and_encrypt(
    content: str,
    output_path: Path,
    sops_config_path: Path | None = None,
) -> None:
    """Write YAML content to a file and encrypt it with SOPS.

    Args:
        content: YAML content to write
        output_path: Path to write the encrypted file
        sops_config_path: Optional path to .sops.yaml config

    Raises:
        RuntimeError: If SOPS encryption fails.
    """
    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write unencrypted content first
    output_path.write_text(content)

    # Build sops command
    cmd = ["sops", "-e", "-i"]

    if sops_config_path:
        cmd.extend(["--config", str(sops_config_path)])

    cmd.append(str(output_path))

    # Run sops encryption
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        # If encryption fails, remove the unencrypted file
        output_path.unlink(missing_ok=True)
        raise RuntimeError(f"SOPS encryption failed: {e.stderr}") from e


def decrypt_file(
    file_path: Path,
    sops_config_path: Path | None = None,
) -> str:
    """Decrypt a SOPS-encrypted file and return its contents.

    Args:
        file_path: Path to the encrypted file
        sops_config_path: Optional path to .sops.yaml config

    Returns:
        Decrypted file contents.

    Raises:
        subprocess.CalledProcessError: If SOPS decryption fails.
    """
    cmd = ["sops", "-d"]

    if sops_config_path:
        cmd.extend(["--config", str(sops_config_path)])

    cmd.append(str(file_path))

    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return result.stdout


def get_nix_repo_root() -> Path | None:
    """Find the root of the Nix repository by looking for flake.nix.

    Returns:
        Path to repository root, or None if not found.
    """
    current = Path.cwd()

    while current != current.parent:
        if (current / "flake.nix").exists():
            return current
        current = current.parent

    return None


def get_secrets_path(hostname: str, repo_root: Path | None = None) -> Path:
    """Get the path where host secrets should be stored.

    NOTE: In the forthcoming multi-identity work (scenario 3), this path
    will gain a `-{namespace}` suffix so one host can hold multiple SOPS
    files (one per identity). For now the legacy `iam-ra.yaml` name is
    kept so scenario-2 work doesn't cascade into path changes.

    Args:
        hostname: Host identifier
        repo_root: Optional repository root path.

    Returns:
        Path to the secrets file.
    """
    if repo_root is None:
        repo_root = get_nix_repo_root()

    if repo_root is None:
        raise RuntimeError("Could not find Nix repository root (flake.nix)")

    return repo_root / "secrets" / "hosts" / hostname / "iam-ra.yaml"
